# Generated by Django 5.1.6 on 2025-02-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="pubs")),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "pub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.pub"
                    ),
                ),
            ],
        ),
    ]
