# Generated by Django 5.1.6 on 2025-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.ImageField(blank=True, upload_to="drinks")),
            ],
        ),
    ]
