# Generated by Django 4.2.19 on 2025-02-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pub', '0002_table_busy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pub.drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'drink')},
            },
        ),
    ]
