# Generated by Django 5.1.6 on 2025-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0002_drink"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="bussy",
            field=models.BooleanField(default=False),
        ),
    ]
